### ISSUE TITLE
OrderedSet?

### ISSUE THREAD

**Issue by NV** [kriskowal/collections#4]
I've noticed there is no OrderedSet here. By OrderedSet I mean:

> A type of Set that has the additional guarantee that the iteration order of values will be the order in which they were added.

If you were to implement an OrderedSet with O(1) `add` and `delete` operations, and a reasonably fast iteration speed, how would you go about it?

(Well, assuming ECMAScript Map/Set/{} property access is O(1)).

Would you use a doubly-linked list as a backend, like in [oset](https://github.com/rse/oset)? While it has O(1) time complexity for `add` and `delete`, iterating over a linked list is slower than a native array.

Asking in public here as somebody else may find this useful too.

**Comment by Stuk** [comment]
According to the documentation, http://www.collectionsjs.com/set Set already tracks insertion order, which can be verified with the code examples. FastSet does not track insertion order.

**Comment by NV** [comment]
Oh, right. I should have RTFM first. Thanks @Stuk!

[set.js](https://github.com/kriskowal/collections/blob/v2/set.js) uses [list.js](https://github.com/kriskowal/collections/blob/v2/list.js) to maintain the order, which is a doubly-linked list. So it's the same algorithm as in [oset](https://github.com/rse/oset).

**Comment by NV** [comment]
I tested iteration speed of a linked list and an array: http://jsperf.com/linked-list-vs-arraw-iteration-speed/2. 
An array is 4-10 times faster, but if we look at the absolute numbers it doesn't matter much anyway.
